[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["rss-parser"]

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/happy-news"
  status = 200

[[redirects]]
  from = "/category/:cat"
  to = "/index.html?category=:cat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
