[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/category/:cat"
  to = "/index.html?category=:cat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
